language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install

script:
  - php vendor/bin/codecept run

cache:
  directories:
    - vendor

branches:
  only:
    - release
